<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>RD.ScreenGuard</AssemblyName>
    <RootNamespace>RD.ScreenGuard</RootNamespace>

    <ApplicationManifest>app.manifest</ApplicationManifest>

    <ApplicationIcon>RD-Screen-Guard.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
